### PR TITLE
Add BlueCat Networks to supporters list, and logo

### PR DESCRIPTION
**Pull request by jdoran-bluecat**
This is in relation to ISC-support #15007 (on behalf of fsoto)

### CODE REVIEW

**Comment by jdoran-bluecat** [comment]
This is in relation to ISC-support #15007 (on behalf of fsoto)

**Comment by jelu** [comment]
And what is `ISC-support #15007` ?

**Comment by jelu** [comment]
And who is `fsoto` ?

**Comment by jelu** [comment]
Okay, starting over with a bit more coffee.

In order for BlueCat to be added as supporter we need a public announcement from an official BlueCat account that they support DNS flag day 2020. It is also good that if it includes something about what BlueCat will do to support this effort, like a blog post about service change that fixes something or makes it better.

**Comment by vrisk** [comment]
Jerry - BlueCat asked ISC to add them to the site as a supporter (that was in the support ticket referenced). I asked them to instead make a direct pull request so that it would be clear that it was BlueCat asking, not ISC. I don't know what versions of BIND BlueCat is shipping, or how they may have modified them, but apparently they intend to support Flag Day, probably by modifying the default buffer size (has that been agreed to yet?)

**Comment by jelu** [comment]
@vrisk I can't verify that @jdoran-bluecat (account created yesterday) is BlueCat and I'm guessing ISC ticket system is not public. That's why BlueCat should announce (twitter, blog post, something) that they support 2020, then we can link to it.

**Comment by jdoran-bluecat** [comment]
Hello, Jerry,

That account @jdoran-bluecat is mine, and I am confirming that by replying from my bluecatnetworks.com<http://bluecatnetworks.com> address.

On Jul 29, 2019, at 1:21 PM, Jerry Lundström <notifications@github.com<mailto:notifications@github.com>> wrote:


@vrisk<https://github.com/vrisk> I can't verify that @jdoran-bluecat<https://github.com/jdoran-bluecat> (account created yesterday) is BlueCat and I'm guessing ISC ticket system is not public. That's why BlueCat should announce (twitter, blog post, something) that they support 2020, then we can link to it.

**Comment by jelu** [comment]
Sorry but there is no way for me to see the email address of the comment,
GitHub hides all that.

You could confirm the request on dns-operations mailing list if you can't
make a public announcement.

**Comment by Mikaela** [comment]
I am not sure if this helps in this case, but have you thought about [verifying your organizations domain in GitHub](https://help.github.com/en/articles/verifying-your-organizations-domain)?

Screenshot from the above link

**Comment by Habbie** [comment]
> BlueCat asked ISC to add them to the site as a supporter (that was in the ISC support ticket referenced)

PowerDNS received the same request, right around the time this PR appeared. I'm merging it.

**Pull request merged**
