### PR TITLE
Spanish translation.

### PR DESCRIPTION
**Pull request by huguei**
Created "es" subdir with spanish translation. Thanks.

### CODE REVIEW

**Comment by pspacek** [comment]
This is now merged, we just need to find out how to create links between versions and how to keep it up to date.

**Comment by pspacek** [comment]
Thank you!

**Comment by pspacek** [comment]
I would recommend you to enable notification for this repo, the translation will need some maintenance ... I just pushed new English version with bunch of changes to the test user interface and few minor other things. I do not speak Spanish so the update is up to you. Good luck!

**Comment by huguei** [comment]
Sure, I'll keep up with the changes and let you know whenever is a new version. Thanks!

**Pull request merged**
