### PR TITLE
Add Japanese translation of 2020 Flag Day

### PR DESCRIPTION
**Pull request by kidmin**
I translated 2020 DNS Flag Day announcement page into Japanese.
Please feel free to use it.

I'm not sure how to update `redirect_from` section; it is kept unchanged.

### CODE REVIEW

**Comment by jelu** [comment]
Thanks. Don't worry about `redirect_from`, I can fix that before merging.

Can you translate the checker also?

Please look in `_data/2020_checker.yml`, copy the whole `en:` session as a new `ja:` section.

**Comment by kidmin** [comment]
Sure.
I pushed a change to `_data/2020_checker.yml`.

I'm going to translate https://github.com/dns-violations/dnsflagday/commit/5fa4f8ddd934e7006b8160ee6d05d9c41c0fbf60#diff-8f52bd708156e89196f0986a1b18f417R327.
Please wait a while.

**Comment by kidmin** [comment]
I added translation about supporters.

Unfortunately a translation of the checker caused conflict.
Can you resolve and merge?

**Comment by jelu** [comment]
Yeah, no worry, I'll fix and merge tomorrow. Thanks!

**Comment by jelu** [comment]
Thanks, merged in #113

**Pull request closed without merging**
