### PR TITLE
add reference to fujiwara draft and date issue.

### PR DESCRIPTION
**Pull request by vixie**
attempting to modernize.

### CODE REVIEW

**Comment by jelu** [comment]
I removed the comment `is arbitary, and controversial`, it feels like a personal view and I don't get it after reading the linked doc. The doc recommends a value between 1220 and 1400, and 1232 is between that.

**Comment by vixie** [comment]
Jerry Lundström wrote on 2019-11-17 23:57:
> I removed the comment |is arbitary, and controversial|, it feels like a 
> personal view and I don't get it after reading the linked doc.

the explaination for it being arbitrary is attached to another issue. i 
will find it and link it here.

it is vital that the dns operations community consider the basis for 
this number, and the impact of various choices.

> The doc recommends a value between 1220 and 1400, and 1232 is between that.
the doc recommends further discussion of the number on the mailing list.

-- 
P Vixie

**Comment by jelu** [comment]
@vixie 

> the doc recommends further discussion of the number on the mailing list.

I can't find any such text.

**Comment by jelu** [comment]
I'm merging this in the meanwhile, we can add more explanations/references once we get the link to them.

**Pull request merged**
