### PR TITLE
Translations of new extended check messages

### PR DESCRIPTION
**Pull request by huguei**
Thanks.

### CODE REVIEW

**Comment by vcunat** [comment]
Uhh, this would best be squashed together before or during merging.

**Comment by pspacek** [comment]
@huguei Awesome, thank you for translation! I have hard time rebasing this to master branch, please be so kind and rebase it locally - it will be easier for your to spot problems because I do not speak Spanish.

```
# while on huguei/dnsflagday/master branch run:
git fetch -a
git rebase -i origin/master
# solve merge conflicts here
git push --force  # into your forked repo
```

Thank you very much!

**Comment by huguei** [comment]
I tried your commands but now it's worst. I see the .cz translations in my patch files :(
I'll put just the diff in a .patch for es/README.md and attach it here.

**Comment by huguei** [comment]
Closed this pull request and added a fresh one https://github.com/dns-violations/dnsflagday/pull/21

**Pull request closed without merging**
