### PR TITLE
Added French translation

### PR DESCRIPTION
**Pull request by ncartron**
Hi,

I created the French translation for the 2020 DNS Flag Day.
It includes also the ISC tester that was added today.

Cheers,
Nico

### CODE REVIEW

**Comment by jelu** [comment]
Thanks!

Can you translate the checker also?

Please look in `_data/2020_checker.yml`, copy the whole `en:` session as a new `fr:` section.

**Comment by ncartron** [comment]
Sure will do it shortly. 

-- 
Nico

**Comment by jelu** [comment]
Last thing before I can merge, can you add this FAQ https://github.com/dns-violations/dnsflagday/commit/5fa4f8ddd934e7006b8160ee6d05d9c41c0fbf60#diff-8f52bd708156e89196f0986a1b18f417R327 ?

**Comment by ncartron** [comment]
> Sure will do it shortly.

done

**Comment by ncartron** [comment]
> Last thing before I can merge, can you add this FAQ [5fa4f8d#diff-8f52bd708156e89196f0986a1b18f417R327](https://github.com/dns-violations/dnsflagday/commit/5fa4f8ddd934e7006b8160ee6d05d9c41c0fbf60#diff-8f52bd708156e89196f0986a1b18f417R327) ?

done

**Comment by jelu** [comment]
uhm, stupid github

**Comment by jelu** [comment]
Merged in https://github.com/dns-violations/dnsflagday/pull/111

**Comment by jelu** [comment]
You might have to re-create your fork since I force updated your master.

**Pull request closed without merging**
