### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by huguei**
Hi. Just as I did for the 2019 campaign, here is the "es" translation for the 2020 site. Thanks.

### CODE REVIEW

**Comment by jelu** [comment]
Thanks!

Can you translate the checker also?

Look in `_data/2020_checker.yml`, copy the `en:` section as a new `es:`.

**Comment by huguei** [comment]
Done! Also corrected an anchor link for the .fr version in 2020_checker.yml

**Comment by jelu** [comment]
Great, thanks!

Will look at this tomorrow.

**Comment by huguei** [comment]
> Done! Also corrected an anchor link for the .fr version in 2020_checker.yml

 @ncartron can you confirm this fix? It's not working currently with the .fr checker.

**Comment by ncartron** [comment]
Do you mean the link to the “Action: Authoritative DNS operators”? 
If so then yes, I let it as English instead of translating it to French. 

-- 
Nico

**Comment by jelu** [comment]
Thanks @huguei !

**Pull request merged**
