### PR TITLE
2020 supporters

### PR DESCRIPTION
**Pull request by jelu**
- Create 2020 support section
  - Add CoreDNS as 2020 supporter https://twitter.com/miekg/status/1144631293210255360
  - Add ISC as 2020 supporter https://twitter.com/ISCdotORG/status/1144649825826160640
  - Add PowerDNS/CZ.NIC
  - Add FAQ about adding supporters

### CODE REVIEW

**Comment by Habbie** [comment]
Please add PowerDNS!

**Comment by pspacek** [comment]
Please add CZ.NIC as well, thank you!

**Comment by pspacek** [comment]
@bjovereinder @ogud @chantra We are compiling list of supporters for 2020, do you want to be listed?

**Comment by bjovereinder** [comment]
You can add NLnet Labs also.  Thanks.

**Comment by johnhtodd** [comment]
I'd like to add Quad9 to the list of official supporters to DNS Flag Day 2020. Thanks!

**Comment by songlinjian** [comment]
Please add Alibaba Cloud to the list of official supporters to DNS Flag Day 2020, thank you!

**Comment by jelu** [comment]
@songlinjian Do you have a link to a logo to use?

**Pull request merged**
