### PR TITLE
New messages for check site owners.

### PR DESCRIPTION
**Pull request by huguei**
And new researchers section.

### CODE REVIEW

**Comment by huguei** [comment]
Hi, is there any problem with this commit? I dropped the previous one and made a new clone, just to be sure not to drag rebase problems. Thanks.

**Comment by pspacek** [comment]
Sorry, I haven't noticed it!

**Comment by pspacek** [comment]
Thank you very much!

**Comment by huguei** [comment]
Thanks to you! It works perfect :+1:

**Pull request merged**
