### PR TITLE
remove scripts from the readme

### PR DESCRIPTION
**Pull request by Formatted**

### CODE REVIEW

**Comment by Habbie** [comment]
Why?

**Comment by Formatted** [comment]
they do not render in the .md markdown file properly, you get unintended content like:
> Your browser does not support JavaScript!
or
> <script> const domainCheckerInit = { placeIntoElement: document.getElementById( "domain-checker" ), texts: { formTitle: 'Test your domain', labelText: 'Domain name (without www): ', submitText: 'Test!', reportOkHtml: ': All Ok!' + '

**Comment by Habbie** [comment]
Right, but they work on https://dnsflagday.net/ which is rendered directly from the .md

**Comment by Formatted** [comment]
got it, strange choice I guess

**Pull request closed without merging**
