### PR TITLE
changed the size of the american flag to match other flags

### PR DESCRIPTION
**Pull request by noika**

### CODE REVIEW

**Comment by pspacek** [comment]
I'm afraid this cannot be done because US flag simply has different aspect ration than other flags, see http://www.usflag.org/flagspecs.html

**Comment by noika** [comment]
But it hurts my eyes! So, can I replace it with a UK flag?

**Comment by pspacek** [comment]
Yes, assuming you translate the text to proper British English :-)

**Comment by pspacek** [comment]
Michal convinced me that it is icon for language and not state flag so it could be okay to crop it.

**Comment by noika** [comment]
My OCD says thank you! ;)

**Pull request merged**
